version: '2'

services:
  rabbitmq:
    container_name: rabbitmq-dev
    build: .
    environment:
      - RABBITMQ_DEFAULT_USER=colus001
      - RABBITMQ_DEFAULT_PASS=12345678
    ports:
      - 85672:5672
      - 95672:15672
